---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: civo
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./infrastructure/provider/civo
  dependsOn:
    - name: global-settings
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
