apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - gateway.yaml
  - virtualservice.yaml
patches:
  - target:
      version: v1
      kind: Namespace
      name: vaultwarden
    path: namespace.yaml
  - target:
      group: cert-manager.io
      version: v1
      kind: Certificate
      name: cert-vaultwarden
    path: certificate.yaml
