apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cnpg
spec:
  interval: 30m
  chart:
    spec:
      chart: cloudnative-pg
      sourceRef:
        kind: HelmRepository
        name: cnpg
      version: "0.27.1"
  driftDetection:
    mode: enabled
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    monitoring:
      podMonitorEnabled: true
      grafanaDashboard:
        create: true

    resources:
      requests:
        cpu: 50m
        memory: 75Mi
      limits:
        memory: 75Mi
