apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
spec:
  interval: 30m
  chart:
    spec:
      chart: grafana
      version: 9.3.1
      sourceRef:
        kind: HelmRepository
        name: grafana
  driftDetection:
    mode: enabled
  values:
    grafana.ini:
      server:
        root_url: https://grafana.rbn.is
      auth.github:
        enabled: true

        auth_url: https://github.com/login/oauth/authorize
        token_url: https://github.com/login/oauth/access_token
        api_url: https://api.github.com/user

        scopes: user:email,read:org
        role_attribute_path: "[login=='rbnis'][0] && 'GrafanaAdmin' || 'None'"
        allow_assign_grafana_admin: true

        allow_sign_up: true
        auto_login: false

    envValueFrom:
      GF_AUTH_GITHUB_CLIENT_ID:
        secretKeyRef:
          name: grafana-auth
          key: oauth-client-id
      GF_AUTH_GITHUB_CLIENT_SECRET:
        secretKeyRef:
          name: grafana-auth
          key: oauth-client-secret

    admin:
      existingSecret: grafana-auth
      userKey: admin-user
      passwordKey: admin-password

    persistence:
      inMemory:
        enabled: true

    resources:
      requests:
        cpu: 10m
        memory: 200Mi
      limits:
        memory: 200Mi

    sidecar:
      datasources:
        enabled: true
        label: grafana_datasource
        defaultDatasourceEnabled: false
      dashboards:
        enabled: true
        label: grafana_dashboard
        searchNamespace: ALL
        provider:
          foldersFromFilesStructure: true
      alerts:
        enabled: true
        label: grafana_alert
        searchNamespace: ALL
      notifiers:
        enabled: true
        label: grafana_notifier
        searchNamespace: ALL
      resources:
        requests:
          cpu: 10m
          memory: 100Mi
        limits:
          memory: 100Mi
