apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
spec:
  interval: 30m
  chart:
    spec:
      chart: grafana
      version: 12.1.0
      sourceRef:
        kind: HelmRepository
        name: grafana-community
  driftDetection:
    mode: enabled
  values:
    grafana.ini:
      server:
        root_url: https://grafana.rbn.is
      auth.generic_oauth:
        enabled: true
        name: Kanidm
        scopes: openid,profile,email,groups
        auth_url: https://auth.rbn.is/ui/oauth2
        token_url: https://auth.rbn.is/oauth2/token
        api_url: https://auth.rbn.is/oauth2/openid/grafana/userinfo
        use_pkce: true
        use_refresh_token: true
        allow_sign_up: true
        allow_assign_grafana_admin: true
        login_attribute_path: preferred_username
        groups_attribute_path: groups
        role_attribute_path: contains(grafana_role[*], 'GrafanaAdmin') && 'GrafanaAdmin' || contains(grafana_role[*], 'Admin') && 'Admin' || contains(grafana_role[*], 'Editor') && 'Editor' || 'Viewer'

    envValueFrom:
      GF_AUTH_GENERIC_OAUTH_CLIENT_ID:
        secretKeyRef:
          name: grafana-auth
          key: oauth-client-id
      GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET:
        secretKeyRef:
          name: grafana-auth
          key: oauth-client-secret

    admin:
      existingSecret: grafana-auth
      userKey: admin-user
      passwordKey: admin-password

    persistence:
      inMemory:
        enabled: true

    resources:
      requests:
        cpu: 25m
        memory: 384Mi
      limits:
        memory: 384Mi

    sidecar:
      datasources:
        enabled: true
        label: grafana_datasource
        defaultDatasourceEnabled: false
      dashboards:
        enabled: true
        label: grafana_dashboard
        searchNamespace: ALL
        provider:
          foldersFromFilesStructure: true
      alerts:
        enabled: true
        label: grafana_alert
        searchNamespace: ALL
      notifiers:
        enabled: true
        label: grafana_notifier
        searchNamespace: ALL
      resources:
        requests:
          cpu: 5m
          memory: 128Mi
        limits:
          memory: 128Mi
