#TODO
apiVersion: v1
kind: Secret
metadata:
  name: lldap-secrets
type: Opaque
stringData:
  # Generate these with: `head -c 32 /dev/urandom | base64`
  LLDAP_JWT_SECRET: "your-jwt-secret"
  LLDAP_KEY_SEED: "your-key-seed"
  LLDAP_LDAP_USER_PASS: "AdminPassword123!"
