---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-vaultwarden
  namespace: istio-ingress
spec:
  secretName: cert-vaultwarden
  commonName: pass.rbn.is
  dnsNames:
    - pass.rbn.is
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
