apiVersion: v1
kind: ConfigMap
metadata:
  name: vaultwarden-config
  labels:
    app.kubernetes.io/name: vaultwarden
data:
  DOMAIN: "https://pass.rbn.is"
  ROCKET_PORT: "8080"
  WEB_VAULT_ENABLED: "true"

  DATA_FOLDER: "/bw-data"

  SIGNUPS_ALLOWED: "false"
  INVITATIONS_ALLOWED: "false"
  SHOW_PASSWORD_HINTS: "false"
