apiVersion: v1
kind: ConfigMap
metadata:
  name: vaultwarden-config
  labels:
    app.kubernetes.io/name: vaultwarden
data:
  DOMAIN: "https://pass.rbn.is"
  ROCKET_PORT: "8080"
  WEB_VAULT_ENABLED: "true"

  DATA_FOLDER: "/bw-data"

  SSO_ENABLED: "true"
  SSO_ONLY: "true"
  SSO_AUTHORITY: "https://auth.rbn.is/oauth2/openid/vaultwarden"
  # # Currently the offline_access acope is not supported by kanidm
  # # See: https://github.com/kanidm/kanidm/issues/4034
  # SSO_SCOPES: "openid profile email offline_access"

  SIGNUPS_ALLOWED: "false"
  INVITATIONS_ALLOWED: "false"
  SHOW_PASSWORD_HINTS: "false"

  # # Configuration of YubiKey OTP
  # # See: https://github.com/dani-garcia/bitwarden_rs#enabling-yubikey-otp-authentication
  # YUBICO_CLIENT_ID: YUBICO_CLIENT_ID
  # YUBICO_SECRET_KEY: YUBICO_SECRET_KEY
