---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vaultwarden
resources:
  - namespace.yaml
  - rbac.yaml
  - config.yaml
  - secrets.sops.yaml
  - certificate.yaml
  - storage.yaml
  - service.yaml
  - deployment.yaml
  - istio.yaml
