---
apiVersion: v1
kind: Service
metadata:
  name: vaultwarden
  namespace: vaultwarden
  labels:
    app.kubernetes.io/name: vaultwarden
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: vaultwarden
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
    - port: 3012
      targetPort: websocket
      protocol: TCP
      name: websocket
