---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: rbnis-blackbox-exporter
  namespace: rbnis
  labels:
    app.kubernetes.io/name: rbnis
spec:
  endpoints:
    - port: http
      scheme: http
      path: "/probe"
      interval: 30s
      scrapeTimeout: 30s
      params:
        module:
          - http_2xx
        target:
          - https://rbn.is
        hostname:
          - rbn.is
      metricRelabelings:
        - sourceLabels: [instance]
          targetLabel: instance
          replacement: https://rbn.is
          action: replace
        - sourceLabels: [target]
          targetLabel: target
          replacement: rbnis-blackbox-exporter
          action: replace
  jobLabel: rbnis-blackbox-exporter
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus-blackbox-exporter
      app.kubernetes.io/instance: prometheus-blackbox-exporter
  namespaceSelector:
    matchNames:
      - observability
