---
creation_rules:
  - path_regex: .*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - age1c5e3523gtu22zh0qphsc0ug8ttdkpm8pcxwcrl5cck62lay2u4fqenpvfq
          - age1vv0w9l4wam5aw2ns0x9tuwkzm942ajyq2setzy7pvpw3waev5qfsakd67a
