---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: cert-manager
resources:
  # renovate: registryUrl=https://charts.jetstack.io chart=cert-manager
  - https://github.com/cert-manager/cert-manager/releases/download/v1.10.0/cert-manager.crds.yaml
