apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: gateway-api-repo
spec:
  interval: 24h
  ref:
    tag: v1.4.1
  url: https://github.com/kubernetes-sigs/gateway-api
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gateway-api-crd
spec:
  interval: 10m
  path: ./config/crd/experimental
  prune: true
  sourceRef:
    kind: GitRepository
    name: gateway-api-repo
