apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-dns
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/controller/external-dns
  components:
    - components/provider/hetzner
    - components/secrets/external
    - components/gateway-api
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
  prune: true
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: external-dns
      namespace: external-dns
