apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gateway-api
spec:
  interval: 10m0s
  dependsOn:
    - name: cilium
    - name: cert-manager
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/config/gateway-api
  components:
    - components/provider/hetzner
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
  prune: true
