apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
spec:
  interval: 30m
  chart:
    spec:
      # renovate: registryUrl=https://charts.jetstack.io/
      chart: cert-manager
      version: v1.19.1
      sourceRef:
        kind: HelmRepository
        name: jetstack
  driftDetection:
    mode: enabled
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    installCRDs: true
    prometheus:
      servicemonitor:
        enabled: true
    tolerations: []
    resources:
      requests:
        cpu: 10m
        memory: 50Mi
      limits:
        memory: 50Mi
    webhook:
      tolerations: []
      resources:
        requests:
          cpu: 10m
          memory: 25Mi
        limits:
          memory: 25Mi
    cainjector:
      tolerations: []
      resources:
        requests:
          cpu: 10m
          memory: 50Mi
        limits:
          memory: 50Mi
    startupapicheck:
      tolerations: []
