apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-api-token
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    name: cloudflare-api-token
    template:
      data:
        api-token: "{{ .token }}"
  data:
    - secretKey: token
      remoteRef:
        key: CLOUDFLARE_TOKEN
