apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-smtp
    labels:
        app.kubernetes.io/name: vaultwarden
type: Opaque
stringData:
    SMTP_HOST: ENC[AES256_GCM,data:JHWbDGHoZX8AmSoZZ8m/W0xVSw==,iv:te56a+iTHtMmQkTmSRc60Eef/hdb8RXomwQzzSJdobQ=,tag:m1fMPRL4cK3oNxQLV66f9w==,type:str]
    SMTP_FROM: ENC[AES256_GCM,data:VUOKF8bPPahtgTaZHgI=,iv:Vz/tWmindUG730cDIer/yKNYaoQ7scAbsUg77Pv6qlE=,tag:1GyRF2k/P+Q9OQ+FrXziwQ==,type:str]
    SMTP_PORT: ENC[AES256_GCM,data:9Qp6,iv:YcAAWDrOJXyt1msi9NHpwZmJ//ATsPJ1QE8Gj3RhnV4=,tag:L2SEyMwgX8MBF/DvOBGJCA==,type:str]
    SMTP_SECURITY: ENC[AES256_GCM,data:zFktx4VJcJU=,iv:0/g59UCyxiZcD+tKbITHIFviztZEiUxBWeYUcADmZEo=,tag:luJGwbKnVi26Si1SYIud7Q==,type:str]
    SMTP_USERNAME: ENC[AES256_GCM,data:3jtexXg5oEj1qTptPUjJGw==,iv:5PhSSJWZa32LdUvRoWfaqszGoUVCEzXaK2JVMpT4KoY=,tag:b4nToLtu4lKz+V2vlkGdmg==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:rbjXIJGo8jFDW9Ci6EvNtQ==,iv:kZ/HAnQ/dT/UM4dfA+DxUvAbxT7v6cFcYSSBhUzyms4=,tag:zolkpsMpEE/y4RJMj1ZxrQ==,type:str]
    SERVER_ADMIN_EMAIL: ENC[AES256_GCM,data:5lpFN3oytO4R2atMjlWcwA/AXLz43DPJmY5UMls8pg==,iv:MzNWlq0Ntri2R6x4KHOgve+BEFMBcoOXyYygi5ipMDU=,tag:USCmatERhaVzWc0TR7IeuQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1c5e3523gtu22zh0qphsc0ug8ttdkpm8pcxwcrl5cck62lay2u4fqenpvfq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkT3V5VkxMeGU4clFQNUFO
            dTBGcGtNNWhQNlFRbzZKSlZXakZBbVgrN1hBCnVoR2xFU25laVl1UThKZjkwcGUx
            WGhxUi85M1ZNNnViKzQ1V2xDa0tUZXcKLS0tIEhXV0xGdTdiemN4VjhycGN5UStH
            QWVaeXpOeGdLaGV5SEtYUjgvUW9QdlUK/9RZEGMR2G5WYLod6plgmzvV9f0PYDPQ
            MbedGrSualjvosuyTxEfukn4u3yhFgY+j2yMz706eSmdJF/uwPdZbQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1vv0w9l4wam5aw2ns0x9tuwkzm942ajyq2setzy7pvpw3waev5qfsakd67a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyRkt0V2VnRVZOU0w5dWM3
            eHVSQUJISXV4bmYxdEV5U2NrbzVlQUd0VGxvCk0vRW5qTVJOMlFFbjBmemlsbGpt
            Y05udkQ0RHpyZnJZQWRmNEsrUDk4R2MKLS0tIElkRnZBZlBSTTB4RDBIWHUwZXVv
            Q1VtYmhnM3lQazNUaG5xL3BJWXZZQ1kKdKMrtn/89PbhdntE3jvlYnvlpwT7yQd9
            YOcKEmZ25w+tRZr88PvEzLHejlEPwCmx71UmxC0lUSbTvae1BI4+QQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ne2905tsuelq4u5g3s0007zanw20z5gjpkpkvctayquhc9pk2q5qvz2q5d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1YUIrRVpnQVNrMUt3V09V
            aEwwU0Q1L21CZW81UmRpQmJ1K3YxbnJkc1FVCmdMbEcrMTUxSWt5WHpWQ3NTUUov
            L1JVN1k0eWI5K0tGMEgxNjhvbUYxb00KLS0tIFY0Z0dMN052RXFXMEVwSHJSb3BH
            Wk5rdUVQNk02eHFJWGlXSE9KYWFkVVkKCd1VyFKHbpz+nHlZO3v9rI1yyoIn486P
            nApzjO0DTDb4v2HfMINnLCBCQuu5+nZhFvrAVk7lMfhiFb7NlEkn7Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-06T20:22:56Z"
    mac: ENC[AES256_GCM,data:pr80cibykVG3Lu0hz0gffpDrESn5Q14FBx3OpMIHm1kVDeflJeD0EUgA5OOiXvHet+KnVswgjUof54vz3h99Yp6n11CztXGdzVke2viw4NyQncxmy9oyHgpWpNEucSX6gQ8ajw1vrqpfPYYRXcRO16wg4FzxgVLHUHiT5L6qGrc=,iv:SBliy8BtjghpJ6alaDEsb2jDEEogIXe4tUDIjj26kHI=,tag:8dQyRqniRU0kEwn8or07cQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
