- op: add
  path: /spec/values/prometheusOperator/tolerations/-
  value:
    key: "kubernetes.azure.com/scalesetpriority"
    operator: "Equal"
    value: "spot"
    effect: "NoSchedule"
- op: add
  path: /spec/values/grafana/tolerations/-
  value:
    key: "kubernetes.azure.com/scalesetpriority"
    operator: "Equal"
    value: "spot"
    effect: "NoSchedule"
- op: add
  path: /spec/values/alertmanager/alertmanagerSpec/tolerations/-
  value:
    key: "kubernetes.azure.com/scalesetpriority"
    operator: "Equal"
    value: "spot"
    effect: "NoSchedule"
- op: add
  path: /spec/values/kube-state-metrics/tolerations/-
  value:
    key: "kubernetes.azure.com/scalesetpriority"
    operator: "Equal"
    value: "spot"
    effect: "NoSchedule"
