---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: rbnis
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./apps/rbnis
  components:
    - components/aks
    - components/istio
  dependsOn:
    - name: crds
    - name: istio-ingress
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
