---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: vaultwarden
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./apps/vaultwarden
  components:
    - components/provider/azure
    - components/secrets/sops
    - components/ingress-nginx
  dependsOn:
    - name: crds
    - name: ingress-nginx
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
