---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: webmontag
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./apps/webmontag
  components:
    - components/aks
    - components/ingress-nginx
  dependsOn:
    - name: ingress-nginx
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
