apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
spec:
  values:
    k8sServiceHost: 127.0.0.1
    k8sServicePort: 6444

    ipam:
      mode: kubernetes
    kubeProxyReplacement: true
    bpf:
      masquerade: false

    gatewayAPI:
      enableProxyProtocol: true
