apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
spec:
  interval: 30m
  chart:
    spec:
      # renovate: registryUrl=https://helm.cilium.io
      chart: cilium
      version: 1.18.0
      sourceRef:
        kind: HelmRepository
        name: cilium
  values:
    encryption:
      enabled: true
      nodeEncryption: true
      type: wireguard

    egressGateway:
      enabled: false

    prometheus:
      enabled: true
      serviceMonitor:
        enabled: true

    resources:
      requests:
        cpu: 50m
        memory: 300Mi
      limits:
        memory: 300Mi

    operator:
      replicas: 1
      prometheus:
        enabled: true
        serviceMonitor:
          enabled: true
      resources:
        requests:
          cpu: 10m
          memory: 100Mi
        limits:
          memory: 100Mi

    envoy:
      resources:
        requests:
          cpu: 10m
          memory: 50Mi
        limits:
          memory: 50Mi

    hubble:
      enabled: true
      metrics:
        enabled:
          - dns
          - drop
          - tcp
          - flow
          - port-distribution
          - icmp
          - httpV2:labelsContext=source_ip,source_namespace,source_workload,destination_ip,destination_namespace,destination_workload,traffic_direction
        serviceMonitor:
          enabled: true

      relay:
        enabled: true
        prometheus:
          enabled: true
          serviceMonitor:
            enabled: true
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
          limits:
            memory: 50Mi

      ui:
        enabled: true
        frontend:
          resources:
            requests:
              cpu: 10m
              memory: 25Mi
            limits:
              memory: 25Mi
        backend:
          resources:
            requests:
              cpu: 10m
              memory: 50Mi
            limits:
              memory: 50Mi
