---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: cilium
  namespace: kube-system
spec:
  interval: 24h
  url: https://helm.cilium.io/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  interval: 30m
  chart:
    spec:
      # renovate: registryUrl=https://helm.cilium.io
      chart: cilium
      version: 1.15.3
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: kube-system
  values:
    gatewayAPI:
      enabled: true
    # bpf:
    #   hostRouting: true -> hostLegacyRouting: true
    kubeProxyReplacement: true
    cgroup:
      autoMount:
        enabled: false
      hostRoot: /sys/fs/cgroup
    # containerRuntime:
    #   integration: containerd
    #   socketPath: /var/run/k3s/containerd/containerd.sock
    operator:
      replicas: 1
