---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cilium
  namespace: kube-system
spec:
  interval: 24h
  url: https://helm.cilium.io/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  interval: 30m
  chart:
    spec:
      # renovate: registryUrl=https://helm.cilium.io
      chart: cilium
      version: 1.16.2
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: kube-system
  values:
    gatewayAPI:
      enabled: true
    kubeProxyReplacement: true
    bpf:
      masquerade: true
      hostLegacyRouting: false
    cgroup:
      autoMount:
        enabled: false
      hostRoot: /sys/fs/cgroup
    operator:
      replicas: 1
