apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
  - target:
      group: helm.toolkit.fluxcd.io
      version: v2
      kind: HelmRelease
      name: kube-prometheus-stack
    path: kube-prometheus-stack.helmrelease.yaml
  - target:
      group: helm.toolkit.fluxcd.io
      version: v2
      kind: HelmRelease
      name: prometheus-blackbox-exporter
    path: prometheus-blackbox-exporter.helmrelease.yaml
  - target:
      group: helm.toolkit.fluxcd.io
      version: v2
      kind: HelmRelease
      name: loki
    path: loki.helmrelease.yaml
  - target:
      group: helm.toolkit.fluxcd.io
      version: v2
      kind: HelmRelease
      name: promtail
    path: promtail.helmrelease.yaml
