apiVersion: gateway.kgateway.dev/v1alpha1
kind: GatewayParameters
metadata:
  name: shared-gateway-logformat
spec:
  kube:
    envoyContainer:
      extraArgs:
        - --log-format
        - '{"timestamp":"%Y-%m-%dT%T.%eZ","level":"%l","message":"%j","scope":"%n"}'
