apiVersion: v1
kind: ConfigMap
metadata:
  name: mimir-datasource
  labels:
    grafana_datasource: "1"
data:
  mimir-datasource.yaml: |-
    apiVersion: 1
    datasources:
      - name: Mimir
        type: prometheus
        isDefault: true
        url: http://mimir.observability.svc.cluster.local:8080/prometheus
        access: proxy
        uid: beubjhhx40qv4a
        jsonData:
          httpMethod: POST
          prometheusType: Mimir
          prometheusVersion: 2.9.1
