apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

resources:
  - service.yaml
  - statefulset.yaml
  - datasource.configmap.yaml

configMapGenerator:
  - name: mimir-config
    files:
      - mimir.yaml=config.yaml
