apiVersion: v1
kind: Service
metadata:
  name: mimir
spec:
  selector:
    app.kubernetes.io/name: mimir
  ports:
    - port: 8080
      name: http
    - port: 9095
      name: grpc
---
apiVersion: v1
kind: Service
metadata:
  name: mimir-headless
  labels:
    app.kubernetes.io/name: mimir
    variant: headless
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: mimir
  ports:
    - name: http
      port: 8080
      targetPort: 8080
    - name: grpc
      port: 9095
      targetPort: 9095
    - name: gossip
      port: 7946
      targetPort: 7946
  publishNotReadyAddresses: true
