apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mimir
  labels:
    app.kubernetes.io/name: mimir
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: mimir
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mimir
    spec:
      containers:
        - name: mimir
          image: grafana/mimir:2.16.1
          args:
            - "-config.file=/etc/mimir/mimir.yaml"
            - "-config.expand-env=true"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: grpc
              containerPort: 9095
              protocol: TCP
            - name: gossip
              containerPort: 7946
              protocol: TCP
            - name: gossip-udp
              containerPort: 7946
              protocol: UDP
          envFrom:
            - secretRef:
                name: mimir-s3
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          volumeMounts:
            - name: config
              mountPath: /etc/mimir
            - name: mimir-data
              mountPath: /data
      volumes:
        - name: config
          configMap:
            name: mimir-config

  volumeClaimTemplates:
    - metadata:
        name: mimir-data
      spec:
        accessModes:
          - ReadWriteOncePod
        resources:
          requests:
            storage: 10Gi
        storageClassName: observability
