apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: flux-system

resources:
  - flux-system
  - cluster-settings.yaml
  - infrastructure
  - apps

patches:
  - target:
      kind: GitRepository
      name: flux-system
      namespace: flux-system
    patch: |
      - op: replace
        path: /spec/ref/branch
        value: apps/observability/rework-lgtm
