apiVersion: v1
kind: Secret
metadata:
    name: azure-account-creds
    namespace: crossplane-system
type: Opaque
stringData:
    credentials: ENC[AES256_GCM,data:Y5nIqTbvNhjaQNA0ccvG+5aNtWQuqQEKw/7czQb9DTN5VONsEsQM5Q/YMTt+X0AWwWo8M90BRtysS5Xl/iLXe/fgQll9cwz3O2WpI+U7cGvEEX8xMWJ0I+I3w5GP4lTcxtOepn1GXugv9fR8V2Fs+oJQ6db+RIFq+wW/iVVfCc2yqKdwBOh2q9bed8ZIPbMoyAFMhO1pC+lGfiixsQz6t3NXYZchoYKVKwedSjF/uv9n8hqCiOEicyrzw0bDNkKs4/mmPk3u+ntw+ICYGOhuED4u+tqW2AG+iDzagvA2OOTcV5GhhxufXuLlqTrePKD/Nb9TUH/U0F+/F/5RWAtKG8Ze0kAMB8L3wupprlrI2+K1JkRHoLnIWVTreY5TRl87BJZmhsX1h6OhwIPz7sdMJl47YobFY9vCOzFDvT1u6Kt0oJ2RG8/1nex4EJhjdzfZUY9x5HUtRr81RsFvWLsJBUeOtljipCjGIGuTUscc7UEeLooR0GD9bRRrVA6NzNWhTR8XDv+LmOAJacqmqRzIObIm6GwcTpOzQp2Efhb2xiiUoL6CsubXg/WHqU/t9Cmjo5TjOG67B44kBk8ddhswLOjkCPcDhRna2NsQwaL/rmdfXvJ72PWfuJlufuyo0My7lLV2zrCMbsMD8sgJd2kvzxJw5pIYloAT6Y6U5HcZJ5aQsJ5uaADGq1xzwcR+eCAdmLJ5MYebfzZaKqIgQr6m7x07hQ4MnJRzT4uZltR8VhJctEIUrEl4rXbHFLqMEjQKF8V6oQEfGdt6UgCpRtanZBEVqClnHftXvMmWMPiUNw/2UO7ehdECIGYLee5byc24H09SmWI=,iv:IucTtMoQ3YEy8Habh1zO1kLnAXL/3QP5eZjNyNqZUUE=,tag:y1fz8XfpJEjLSBPimIIWNA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1c5e3523gtu22zh0qphsc0ug8ttdkpm8pcxwcrl5cck62lay2u4fqenpvfq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLdndQS1RWTVJwQmpkY015
            NDJSUDdpeDZoNjJKeEdWdTBWQXVFR2VoNVJRCmNXMGhiYlFidGRPRkJ0eGlWeElH
            UUxpeFpBcDZhQUlsQmFLaGlWbk55UjQKLS0tIFltVE1mNDZJZ2pMcUtMVlFJVTMx
            UXFJTHZMME5nTjRveUJTcDJZS2lpUFUKpQljPLS297apSQmGRfYF/rDbAR2aSjUu
            0yT+cEUoG8zg8BxmX3yMeiQsw3bkl9iB29ZymP/EZVMgaoQT1flC3A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1vv0w9l4wam5aw2ns0x9tuwkzm942ajyq2setzy7pvpw3waev5qfsakd67a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwN1JoMWx3MTJsQThnOXh6
            NjlQY0g0dnp3MDBrbFdLRk9ETlBjYThHL0FFCm9udGZaVVV3QjBtcFIxUkYxZ0xl
            UU5sRXhLMDl3VDU1UUc5cEk0V0s3STgKLS0tIE5mTlZ6OExSWnNBZVN5bm1nWUFM
            Q21MUWdqYkhoejFmSDVzb1Q1R1c4UDAKlM4F1iOlgK29CBKyNnY0UmuSI4oklDtL
            BzYVaU6A6SPwbF8jg5t0JWwrNgNnFuIzJFV0wXZHF3MLt3aoliPzkw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-10-29T13:33:21Z"
    mac: ENC[AES256_GCM,data:5l6jr5sKT7NSKBW2csVv/kSBj7l9ZzhCPFWMt/a0WUJuZM/FSffTc63wKi48siTWmM7BIjaexqeDx+V/m3OeatSAIww04saugs5BoEB8p/0qQ6c9+5vlx0TEKoehW4y6I4XXg4aME7I0IDXJquKdiWIteeblwBOCVQThzCMvVUI=,iv:KN3ksKZ6LzYvxKNxxUjKk15AJbG83/O1AFRUTdP+0m0=,tag:pHkFe7npNYL5LHZ6qqLSfg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
