apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kanidm-smtp
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    name: kanidm-smtp
    template:
      data:
        username: "{{ .username }}"
        password: "{{ .password }}"
  data:
    - secretKey: username
      remoteRef:
        key: MAILERSEND_SMTP_USERNAME
    - secretKey: password
      remoteRef:
        key: MAILERSEND_SMTP_PASSWORD
