apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
  - target:
      group: helm.toolkit.fluxcd.io
      version: v2
      kind: HelmRelease
      name: external-dns
    patch: |
      - op: add
        path: /spec/values/sources/-
        value: istio-gateway
