---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-ingressgateway
  namespace: istio-ingress
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://istio-release.storage.googleapis.com/charts
      chart: gateway
      version: 1.18.3
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
  values:
    resources:
      requests:
        cpu: 50m
        memory: 256Mi
      limits:
        cpu: null
        memory: 256Mi
