apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin
    namespace: observability
    labels:
        app.kubernetes.io/name: grafana
        app.kubernetes.io/component: config
stringData:
    username: ENC[AES256_GCM,data:Sm+DrW0=,iv:NmdenDYVQcqUvHv8O4uxIA2cnxYQoz/AgiqUvwkuqhE=,tag:iZeTVaG9yLQtAep9s7TKsw==,type:str]
    password: ENC[AES256_GCM,data:/rvHX+2TcDzmozJIF8iTTfwGP3t90JUDaOUEKJgawMcWNEDqsmcv4LfE,iv:RQe+dl0fjoqPka0iMdY54mbsMDSoTJR1f9iet03yZr4=,tag:JrLplBC0v7b10LkKT8FOYA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1c5e3523gtu22zh0qphsc0ug8ttdkpm8pcxwcrl5cck62lay2u4fqenpvfq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5aUE4M1I3M3Y0K0VIWnJu
            VlhjZGNDOFRSMjFEakwrbnpTWFBueHhQVFd3CkY0WURZQWZLSGJWVzRCVFVwYmFI
            dURKdENJSzBLQVdVNC9lTDdyNCtxbDAKLS0tIGVueFVsR215NHB0U1BnSlZjTUNL
            ZW5vSWZrRmtvRHE1VCt1TEt2QWhQSW8KpNPF/clbX44njHIvvsokNiXz96GF/eZh
            AUDjjLGeWW3b4raylGa4eGactWU9gXixUn2FJE39LTSVIAGj8yr0wg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1vv0w9l4wam5aw2ns0x9tuwkzm942ajyq2setzy7pvpw3waev5qfsakd67a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOM1AwUWZ4SDJIdFNHWkJv
            UjFPZTJoek0yMksvWXZCTUplQ0dZVHgvVENrCkpndWVpTjQrd3dxaEFoVEc1ZXFC
            aEtKSXBGekV6RDFrOTUxcEpiTmM4bUEKLS0tIDQ5bVA3STJ1WHE2NkRTV2FKTktx
            Q2tLbVQySmo3TTBxcDBjYTV5Nm5rTGcKOTpLjE69eeTVJJyTCPmbPUiLjgU7AEJE
            6ER/WD6TuiBUuzhpH3SlnumnQ4T2pRgxcmx8lEZcJSKt4c+V3TmS2g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-12T14:15:02Z"
    mac: ENC[AES256_GCM,data:M6JWPUdX1o/hO4glPGGWX7uvGm7PjbYxrp++gRmSUr7lm9wQaEDtgZPqjfa7ckYOXBFcUjIzroB9ogK12HJ6vO/M7MzyZtSds2B7kN6DTfqYCdZAk+K/URirYlBmIxX99CMJ0bcGcv911xvyJs9x1VyBUxP8k+CmEupfQZr0e+Q=,iv:c3+HwuFvv1BqWNoPtkdZnU2r17DqcYx5HqSiB3XnyCQ=,tag:4FWodnr3Y8Ay/99l+aIwjA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
