apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - "namespace.yaml"
  - "grafana-admin.secret.sops.yaml"
  - "grafana-notifiers.sectret.sops.yaml"
  - "helmrepository.yaml"
  - "kube-prometheus-stack.helmrelease.yaml"
  - "certificate.yaml"
