apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - grafana-admin.secret.sops.yaml
  - client-auth-ca.secret.sops.yaml
  - grafana-notifiers.secret.sops.yaml
  - loki-storage.secret.sops.yaml
  - helmrepository.yaml
  - kube-prometheus-stack.helmrelease.yaml
  - prometheus-blackbox-exporter.helmrelease.yaml
  - loki.helmrelease.yaml
  - loki-datasource.configmap.yaml
  - promtail.helmrelease.yaml
  - certificate.yaml
configMapGenerator:
  - name: alerts-certificates
    namespace: observability
    files:
      - alerts/certificates.yaml
    options:
      disableNameSuffixHash: true
      labels:
        grafana_alert: "1"
  - name: notificationpolicy
    namespace: observability
    files:
      - notifications/notificationpolicy.yaml
    options:
      disableNameSuffixHash: true
      labels:
        grafana_alert: "1"
secretGenerator:
  - name: contactpoints
    namespace: observability
    files:
      - contactpoints.yaml=notifications/contactpoints.sops.yaml
    options:
      disableNameSuffixHash: true
      labels:
        grafana_alert: "1"
