apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: observability
spec:
  interval: 30m
  chart:
    spec:
      # renovate: registryUrl=https://grafana.github.io/helm-charts
      chart: loki
      version: 6.7.3
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: observability
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    deploymentMode: SingleBinary
    loki:
      auth_enabled: false
      commonConfig:
        replication_factor: 2
      limits_config:
        retention_period: 30d
      compactor:
        retention_enabled: true
        delete_request_store: azure
        working_directory: /var/loki/data/retention
        compaction_interval: 10m
        retention_delete_delay: 2h
        retention_delete_worker_count: 150
      schemaConfig:
        configs:
          - from: "2024-01-01"
            store: tsdb
            index:
              prefix: loki_index_
              period: 24h
            object_store: azure
            schema: v13
      rulerConfig:
        storage:
          type: local
          local:
            directory: /loki/rules
        rule_path: /tmp/rules/fake/
        alertmanager_url: http://kube-prometheus-stack-alertmanager:9093
        ring:
          kvstore:
            store: inmemory
        enable_api: true
      storage:
        type: 'azure'
    singleBinary:
      replicas: 2
      tolerations: []
    chunksCache:
      allocatedMemory: 512
      resources:
        requests:
          cpu: 50m
      tolerations: []
    resultsCache:
      allocatedMemory: 256
      resources:
        requests:
          cpu: 50m
      tolerations: []
    read:
      replicas: 0
    backend:
      replicas: 0
    write:
      replicas: 0
    lokiCanary:
      tolerations: []
    gateway:
      tolerations: []

  valuesFrom:
    - kind: Secret
      name: loki-storage
