apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    grafana_datasource: "1"
  name: loki-datasource
  namespace: observability
data:
  datasources.yaml: |-
    apiVersion: 1
    datasources:
      - name: Loki
        type: loki
        url: http://loki-gateway
        access: proxy
        jsonData:
          maxLines: 1000
          timeout: 1800
