apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: promtail
  namespace: observability
spec:
  interval: 30m
  chart:
    spec:
      # renovate: registryUrl=https://grafana.github.io/helm-charts
      chart: promtail
      version: 6.16.6
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: observability
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    config:
      logLevel: warn
      logFormat: json
    resources: {}
    tolerations: []
