apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus-blackbox-exporter
  namespace: observability
spec:
  interval: 30m
  chart:
    spec:
      # renovate: registryUrl=https://prometheus-community.github.io/helm-charts
      chart: prometheus-blackbox-exporter
      version: 9.4.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: observability
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    config:
      modules:
        http_2xx:
          prober: http
          timeout: 5s
          http:
            valid_http_versions: ["HTTP/1.1", "HTTP/2", "HTTP/2.0"]
            headers:
              Accept: "*/*"
            follow_redirects: true
            preferred_ip_protocol: "ip4"
    serviceMonitor:
      enabled: true
    pspEnabled: false
    resources:
      requests:
        cpu: 20m
        memory: 100Mi
      limits:
        memory: 100Mi
    tolerations: []
