---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webmontag
  namespace: webmontag
  labels:
    app.kubernetes.io/name: webmontag
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: webmontag
  template:
    metadata:
      labels:
        app.kubernetes.io/name: webmontag
    spec:
      automountServiceAccountToken: false
      containers:
        - name: webmontag
          image: ghcr.io/rbnis/webmontag:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
          resources:
            requests:
              cpu: 25m
              memory: 20Mi
            limits:
              memory: 20Mi
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          securityContext:
            runAsUser: 101
            runAsGroup: 101
            fsGroup: 101
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                topologyKey: "kubernetes.io/hostname"
                labelSelector:
                  matchExpressions:
                    - key: "app.kubernetes.io/name"
                      operator: In
                      values:
                        - webmontag
      tolerations: []
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: webmontag
  namespace: webmontag
spec:
  maxUnavailable: 50%
  selector:
    matchLabels:
      app.kubernetes.io/name: webmontag
