---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: rbnis
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./apps/rbnis
  dependsOn:
    - name: crds
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
