apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
spec:
  interval: 30m
  chart:
    spec:
      chart: loki
      version: 6.35.0
      sourceRef:
        kind: HelmRepository
        name: grafana
  driftDetection:
    mode: enabled
  values:
    deploymentMode: SingleBinary
    singleBinary:
      replicas: 2
      extraArgs:
        - -config.expand-env=true
      extraEnvFrom:
        - secretRef:
            name: loki-s3

      persistence:
        storageClass: observability

      resources:
        requests:
          cpu: 50m
          memory: 512Mi
        limits:
          memory: 768Mi

    loki:
      auth_enabled: false

      commonConfig:
        replication_factor: 2

      storage:
        bucketNames:
          chunks: ${S3_BUCKET}
          ruler: ${S3_BUCKET}
          admin: ${S3_BUCKET}
        type: s3
        s3:
          # s3: "s3://xxxxx-loki"
          # endpoint: s3.us-east-1.amazonaws.com/path/prefix
          endpoint: ${S3_ENDPOINT}
          accessKeyId: ${AWS_ACCESS_KEY_ID}
          secretAccessKey: ${AWS_SECRET_ACCESS_KEY}
          s3ForcePathStyle: true
          insecure: false

      schemaConfig:
        configs:
          - from: "2024-04-01"
            store: tsdb
            object_store: s3
            schema: v13
            index:
              prefix: loki_index_
              period: 24h

      pattern_ingester:
        enabled: true
      limits_config:
        retention_period: 30d
        allow_structured_metadata: true
        volume_enabled: true
      ruler:
        enable_api: true

      compactor:
        retention_enabled: true
        delete_request_store: s3
        working_directory: /var/loki/compactor
        compaction_interval: 10m
        retention_delete_delay: 2h
        retention_delete_worker_count: 150

      podDisruptionBudget:
        maxUnavailable: 1

    lokiCanary:
      resources:
        requests:
          cpu: 10m
          memory: 50Mi
        limits:
          memory: 50Mi

    gateway:
      resources:
        requests:
          cpu: 10m
          memory: 25Mi
        limits:
          memory: 25Mi

    chunksCache:
      allocatedMemory: 512
      resources:
        requests:
          cpu: 10m
          memory: 50m
        limits:
          memory: 50m
    resultsCache:
      allocatedMemory: 256
      resources:
        requests:
          cpu: 10m
          memory: 25Mi
        limits:
          memory: 25Mi

    # Zero out replica counts of other deployment modes
    backend:
      replicas: 0
    read:
      replicas: 0
    write:
      replicas: 0
    ingester:
      replicas: 0
    querier:
      replicas: 0
    queryFrontend:
      replicas: 0
    queryScheduler:
      replicas: 0
    distributor:
      replicas: 0
    compactor:
      replicas: 0
    indexGateway:
      replicas: 0
    bloomCompactor:
      replicas: 0
    bloomGateway:
      replicas: 0



# loki-gateway-cddc6cc6b-mdztr
