apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vaultwarden-smtp
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    name: vaultwarden-smtp
    template:
      data:
        SMTP_HOST: smtp.mailersend.net
        SMTP_PORT: "587"
        SMTP_SECURITY: starttls
        SMTP_USERNAME: "{{ .username }}"
        SMTP_PASSWORD: "{{ .password }}"
        SMTP_FROM: noreply@rbn.is
        SERVER_ADMIN_EMAIL: "{{ .adminMail }}"
  data:
    - secretKey: username
      remoteRef:
        key: MAILERSEND_SMTP_USERNAME
    - secretKey: password
      remoteRef:
        key: MAILERSEND_SMTP_PASSWORD
    - secretKey: adminMail
      remoteRef:
        key: VAULTWARDEN_ADMIN_EMAIL
