apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vaultwarden-sso
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    name: vaultwarden-sso
    template:
      data:
        SSO_ENABLED: "true"
        SSO_ONLY: "true"
        SSO_AUTH_ONLY_NOT_SESSION: "true"
        SSO_AUTHORITY: "https://auth.rbn.is/oauth2/openid/vaultwarden"
        SSO_CLIENT_ID: "{{ .clientID }}"
        SSO_CLIENT_SECRET: "{{ .clientSecret }}"
        # # Currently the offline_access acope is not supported by kanidm
        # # See: https://github.com/kanidm/kanidm/issues/4034
        # SSO_SCOPES: "openid profile email offline_access"
  data:
    - secretKey: clientID
      remoteRef:
        key: VAULTWARDEN_AUTH_KANIDM_CLIENT_ID
    - secretKey: clientSecret
      remoteRef:
        key: VAULTWARDEN_AUTH_KANIDM_CLIENT_SECRET
