apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vaultwarden-sso
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    name: vaultwarden-sso
    template:
      data:
        SSO_CLIENT_ID: "{{ .clientID }}"
        SSO_CLIENT_SECRET: "{{ .clientSecret }}"
  data:
    - secretKey: clientID
      remoteRef:
        key: VAULTWARDEN_AUTH_KANIDM_CLIENT_ID
    - secretKey: clientSecret
      remoteRef:
        key: VAULTWARDEN_AUTH_KANIDM_CLIENT_SECRET
