---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: grafana-agent-logs
  namespace: grafana-agent
spec:
  minReadySeconds: 10
  selector:
    matchLabels:
      name: grafana-agent-logs
  template:
    metadata:
      labels:
        name: grafana-agent-logs
    spec:
      containers:
        - args:
            - -config.file=/etc/agent/agent.yaml
            - -config.expand-env
            - -server.http.address=0.0.0.0:80
            - -disable-reporting
          command:
            - /bin/agent
          env:
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          envFrom:
            - secretRef:
                name: grafana-agent
          image: grafana/agent:v0.27.1
          imagePullPolicy: IfNotPresent
          name: grafana-agent-logs
          ports:
            - containerPort: 80
              name: http-metrics
          securityContext:
            privileged: true
            runAsUser: 0
          volumeMounts:
            - mountPath: /etc/agent
              name: grafana-agent-logs
            - mountPath: /var/log
              name: varlog
            - mountPath: /var/lib/docker/containers
              name: varlibdockercontainers
              readOnly: true
      serviceAccount: grafana-agent-logs
      tolerations:
        - effect: NoSchedule
          operator: Exists
      volumes:
        - configMap:
            name: grafana-agent-logs
          name: grafana-agent-logs
        - hostPath:
            path: /var/log
          name: varlog
        - hostPath:
            path: /var/lib/docker/containers
          name: varlibdockercontainers
  updateStrategy:
    type: RollingUpdate
