---
kind: ConfigMap
metadata:
  name: grafana-agent-logs
  namespace: grafana-agent
apiVersion: v1
data:
  agent.yaml: |
    metrics:
      wal_directory: /tmp/grafana-agent-wal
      global:
        scrape_interval: 60s
        external_labels:
          cluster: rbnis-infra-aks-v1
      configs:
      - name: integrations
        remote_write:
        - url: ${prometheus_remote}
          basic_auth:
            username: ${prometheus_username}
            password: ${prometheus_password}
    integrations:
      prometheus_remote_write:
      - url: ${prometheus_remote}
        basic_auth:
          username: ${prometheus_username}
          password: ${prometheus_password}

    logs:
      configs:
      - name: integrations
        clients:
        - url: ${loki_remote}
          basic_auth:
            username: ${loki_username}
            password: ${loki_password}
          external_labels:
            cluster: rbnis-infra-aks-v1
        positions:
          filename: /tmp/positions.yaml
        target_config:
          sync_period: 10s
        scrape_configs:
        - job_name: integrations/kubernetes/pod-logs
          kubernetes_sd_configs:
            - role: pod
          pipeline_stages:
            - cri: {}
            - match:
                selector: '{app="rbnis"}'
                stages:
                  - drop:
                      expression: '.*kube-probe.*'
                  - regex:
                      expression: '^(?P<remote_addr>[\w\.]+) - (?P<remote_user>[^ ]*) \[(?P<time_local>.*)\] "(?P<method>[^ ]*) (?P<request>[^ ]*) (?P<protocol>[^ ]*)" (?P<status>[\d]+) (?P<body_bytes_sent>[\d]+) "(?P<http_referer>[^"]*)" "(?P<http_user_agent>[^"]*)"?'
                  - labels:
                      method:
                      request:
                      status:
          relabel_configs:
            - source_labels:
                - __meta_kubernetes_pod_node_name
              target_label: __host__
            - action: labelmap
              regex: __meta_kubernetes_pod_label_(.+)
            - action: replace
              replacement: $1
              separator: /
              source_labels:
                - __meta_kubernetes_namespace
                - __meta_kubernetes_pod_name
              target_label: job
            - action: replace
              source_labels:
                - __meta_kubernetes_namespace
              target_label: namespace
            - action: replace
              source_labels:
                - __meta_kubernetes_pod_name
              target_label: pod
            - action: replace
              source_labels:
                - __meta_kubernetes_pod_container_name
              target_label: container
            - replacement: /var/log/pods/*$1/*.log
              separator: /
              source_labels:
                - __meta_kubernetes_pod_uid
                - __meta_kubernetes_pod_container_name
              target_label: __path__
