---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: grafana-agent
  namespace: grafana-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      name: grafana-agent
  serviceName: grafana-agent
  template:
    metadata:
      labels:
        name: grafana-agent
    spec:
      containers:
        - args:
            - -config.file=/etc/agent/agent.yaml
            - -config.expand-env
            - -enable-features=integrations-next
            - -server.http.address=0.0.0.0:80
            - -disable-reporting
          command:
            - /bin/agent
          env:
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          envFrom:
            - secretRef:
                name: grafana-agent
          image: grafana/agent:v0.28.0
          imagePullPolicy: IfNotPresent
          name: grafana-agent
          ports:
            - containerPort: 80
              name: http-metrics
          volumeMounts:
            - mountPath: /var/lib/agent
              name: agent-wal
            - mountPath: /etc/agent
              name: grafana-agent
      serviceAccount: grafana-agent
      volumes:
        - configMap:
            name: grafana-agent
          name: grafana-agent
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: agent-wal
        namespace: grafana-agent
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
