apiVersion: v1
kind: Secret
metadata:
    name: grafana-agent
    namespace: grafana-agent
stringData:
    prometheus_remote: ENC[AES256_GCM,data:f1ljtJUTEuO1Q83CHIivCGChwBm2wklCtVBPKO70SBHkvDfZ+XspkeEVq5lnZQFKznXYhpFEsRguHvzNycY=,iv:aJ2aFbo8ysOh4jffkxkQ7hNbDl8AAvbnUGZMlQzr11M=,tag:xfGaFWiw+QwTClOAAF/hsA==,type:str]
    prometheus_username: ENC[AES256_GCM,data:E4pctI7f,iv:S+MEA5SH1z3+aNt5PxUc7A8uST0KCQ8dB9Oj22YniH0=,tag:MZ1rpbLbc9v59ydI94DtoQ==,type:str]
    prometheus_password: ENC[AES256_GCM,data:0EF7jmv72FHjjw64CLSaRKn/Bkh5zZOenB7qmJryI/BlPmN1dPpw7C8+E3C5lYUJDIQQ+PjDPPPm0WufGGwRrWAsUmpET2CfQBxsL5hXxZyhKggMEpO/8xiS4G6WoOH/Oq9v8MSwr7TZegpKS29vZAE585v7bUSNYpG7cEqs7PkVDNIf27zuzr2qFI+loZhdoNQov5BcnMw=,iv:Up70RyhOr1hARIn+IWWduTxsjH758ecxBJoWo5U2VeQ=,tag:COHTD/Qi05nggmV2OHbeKQ==,type:str]
    loki_remote: ENC[AES256_GCM,data:ARGQPn9Z07whSwOOWXByoAtI/dqkPsmaauWoAPlPbujGNQ7WbfeJe4F6r34cB5A2lG7+2fzxy7g=,iv:9HjcV89g8etDGVCswSOnNKnI8ZT0lAzwPe6SJrGgjX8=,tag:O6LgiAphZ1Xd564CepZE6w==,type:str]
    loki_username: ENC[AES256_GCM,data:IBwrrRxk,iv:Iu2DQi2UdV+DnKrYbVzjJIvn1ttePttJw1dtxKXer/M=,tag:Nh7eZQffTs3lEQEZcleS5w==,type:str]
    loki_password: ENC[AES256_GCM,data:dNoAnXJk4UVxA3yQGHzUVji1JprTTcr3Bu0xff9PaRA9/Es1wOLQd8z4OSYvE1iY8RIS+33jptK8VT8ppEqMIO/qSRNUDRP2FPOdpvDYb2cCIeTqYGIei1HD5qAtgd5DZzce9/U/eKuSmy2mxfnhOC/vxdl4nlO98lLSsdbfaYE02BCzhebKQRO/cq9s3SgQfwCxAw==,iv:QcJ9UW4+fRBroUM5SW5rTBYFpKHvRIZlTGVuifGmXWY=,tag:GTcPVClouFiow+ijN4suKg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1c5e3523gtu22zh0qphsc0ug8ttdkpm8pcxwcrl5cck62lay2u4fqenpvfq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSaVJTeEdOeHBYc3psUXlq
            SUZBMmw4b0N3ZFpaRjczMDdtMW11SzNWNkFVCnRVelUvSDlyQXluRXNEYTV6aGlk
            Znpyb0R2dkwrT3BWbmVlOUFGdnFVSzAKLS0tIEpGaDAwTnk2a1kzcURrWThmWm5C
            T2dLM21sSk9kRXF5aUxhdkw1Z2xmMFEKvsiYHVZhUytviNN0OUGVQcEi+SMx4Rt/
            6zKUBqg2mavcjvxiy0jcNHXPZayoj63TBlJOve7CJkvYZ0SV1l0W8Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1vv0w9l4wam5aw2ns0x9tuwkzm942ajyq2setzy7pvpw3waev5qfsakd67a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqNUY3c3R3OTBNeFlUQ2RS
            T3NVd09YUzhkWXptYXJoRnJ6SjJxb1o2eUVvCkV4a2FrNjhUMFk4V2xUYyt5M21M
            RHUzNWo1RWx4WVczTlVyT3dieHVSZVUKLS0tIHdKRUQ5TnJVN0dVc1B0MW55NUxt
            bndxZlJPRjZ6aU91OHp3d2Zub0dIdUEKBwWQKIU7nH7Xt9+6CtMDIga94dNFg9kr
            0SWquqH6c6MnudQDfYdPjkuoUAC2iy03Q1RCge0ynI48ni/KfdvuvQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-06T21:11:32Z"
    mac: ENC[AES256_GCM,data:BEml3XbVzpM2vtXD9b6MyzEZUzadxxYKPQVMBjnjviVeT1afNBTWSg8aaZHHOQRqg5eIIP7G0cPpGOc3ezugMlZvU2HH7UBIoVYyKT6T++rxV5N7Vqc7m8ftEiL6uBH6TqF6mG4bORtKGMXkBaabiCe67MT6famcbVnAPLFyPY4=,iv:p832hevY8So9LLqqLGdJlReerdlszrrgiI96HqAZToc=,tag:8nh/ydoSlvs7gr4g8gmpcg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
