apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: vaultwarden
    path: deployment.yaml
  - target:
      group: ""
      version: v1
      kind: PersistentVolumeClaim
      name: vaultwarden-data-pvc
    path: persistentvolumeclaim.yaml
