---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://kubernetes-sigs.github.io/external-dns/
      chart: external-dns
      version: 1.11.0
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
  values:
    serviceMonitor:
      enabled: false
    provider: cloudflare
    env:
      - name: CF_API_TOKEN
        valueFrom:
          secretKeyRef:
            name: cloudflare-api-token
            key: api-token
    sources:
      # - service
      # - ingress
      - istio-gateway
      # - istio-virtualservice
    policy: upsert-only #TODO
    txtOwnerId: "${cluster_name}"
    logFormat: json
    tolerations:
      - key: "kubernetes.azure.com/scalesetpriority"
        operator: "Equal"
        value: "spot"
        effect: "NoSchedule"
