---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istiod
  namespace: istio-system
spec:
  dependsOn:
    - name: istio-base
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://istio-release.storage.googleapis.com/charts
      chart: istiod
      version: 1.17.1
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
  values:
    global:
      logAsJson: true
      proxy:
        resources:
          limits: null
    pilot:
      resources:
        requests:
          cpu: 250m
          memory: 1024Mi

