---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-base
  namespace: istio-system
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://istio-release.storage.googleapis.com/charts
      chart: base
      version: 1.16.0
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
