apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - gateway.yaml
  - virtualservice.yaml
patches:
  - target:
      version: v1
      kind: Namespace
      name: rbnis
    path: namespace.yaml
