---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: autoscaler
  namespace: kube-system
spec:
  interval: 24h
  url: https://kubernetes.github.io/autoscaler
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: autoscaler
  namespace: kube-system
spec:
  interval: 30m
  chart:
    spec:
      chart: cluster-autoscaler
      version: "9.36.0"
      sourceRef:
        kind: HelmRepository
        name: autoscaler
        namespace: kube-system
  values:
    cloudProvider: civo
    autoscalingGroups:
      - name: pool1
        minSize: 1
        maxSize: 3
    extraArgs:
      skip-nodes-with-local-storage: false
      skip-nodes-with-system-pods: false
    extraEnvSecrets:
      CIVO_API_URL:
        name: civo-api-access
        key: api-url
      CIVO_API_KEY:
        name: civo-api-access
        key: api-key
      CIVO_CLUSTER_ID:
        name: civo-api-access
        key: cluster-id
      CIVO_REGION:
        name: civo-api-access
        key: region
    deployment:
      annotations:
        prometheus.io/port: "8085"
        prometheus.io/scrape: "true"
    resources:
      requests:
        cpu: 100m
        memory: 300Mi
      limits:
        memory: 300Mi
