apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-state-metrics
spec:
  interval: 30m
  chart:
    spec:
      chart: kube-state-metrics
      version: 6.1.3
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
  driftDetection:
    mode: enabled
  values:
    prometheus:
      monitor:
        enabled: true
    resources:
      requests:
        cpu: 20m
        memory: 50Mi
      limits:
        memory: 50Mi
