---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./infrastructure/controller/ingress-nginx
  dependsOn:
    - name: crds
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
