apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kured
spec:
  interval: 30m
  chart:
    spec:
      chart: kured
      sourceRef:
        kind: HelmRepository
        name: kured
      version: "5.6.2"
  driftDetection:
    mode: enabled
  values:
    metrics:
      create: true
    resources:
      requests:
        cpu: 10m
        memory: 25Mi
      limits:
        memory: 25Mi
