apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
spec:
  interval: 30m
  chart:
    spec:
      # renovate: registryUrl=https://kubernetes-sigs.github.io/external-dns/
      chart: external-dns
      version: 1.19.0
      sourceRef:
        kind: HelmRepository
        name: external-dns
  driftDetection:
    mode: enabled
  values:
    serviceMonitor:
      enabled: true
    provider: cloudflare
    env:
      - name: CF_API_TOKEN
        valueFrom:
          secretKeyRef:
            name: cloudflare-api-token
            key: api-token
    sources:
      - ingress
    txtOwnerId: "${cluster_name}"
    policy: sync
    logFormat: json
    tolerations: []
    extraArgs: []
    resources:
      requests:
        cpu: 10m
        memory: 50Mi
      limits:
        memory: 50Mi
