apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: observability
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/observability
  components:
    - components/provider/hetzner
    - components/secrets/external
    - components/gateway-api
  prune: true
