apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: vaultwarden
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/vaultwarden
  components:
    - components/provider/hetzner
    - components/secrets/external
    - components/gateway-api
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
  prune: true
