---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tf-controller
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: tf-controller
      version: '0.15.1'
      sourceRef:
        kind: HelmRepository
        name: tf-controller
        namespace: flux-system
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    resources:
      requests:
        cpu: 200m
        memory: 128Mi
      limits:
        memory: 128Gi
