apiVersion: kaniop.rs/v1beta1
kind: KanidmGroup
metadata:
  name: grafana-access
spec:
  kanidmRef:
    name: rbnis
  members:
    - robin
---
apiVersion: kaniop.rs/v1beta1
kind: KanidmGroup
metadata:
  name: grafana-superadmins
spec:
  kanidmRef:
    name: rbnis
  members:
    - robin
---
apiVersion: kaniop.rs/v1beta1
kind: KanidmGroup
metadata:
  name: grafana-admins
spec:
  kanidmRef:
    name: rbnis
  members: []
---
apiVersion: kaniop.rs/v1beta1
kind: KanidmGroup
metadata:
  name: grafana-editors
spec:
  kanidmRef:
    name: rbnis
  members: []
