apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kgateway-crds
spec:
  interval: 30m
  chart:
    spec:
      chart: kgateway-crds
      sourceRef:
        kind: HelmRepository
        name: kgateway
      version: "v2.2.1"
  driftDetection:
    mode: enabled
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kgateway
spec:
  interval: 30m
  chart:
    spec:
      chart: kgateway
      sourceRef:
        kind: HelmRepository
        name: kgateway
      version: "v2.2.1"
  dependsOn:
    - name: kgateway-crds
  driftDetection:
    mode: enabled
