apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: vaultwarden
spec:
  parentRefs:
    - name: shared-gateway
      namespace: infra
      sectionName: https
  hostnames:
    - "pass.rbn.is"
  rules:
    - backendRefs:
        - name: vaultwarden
          port: 80
