apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: auth
spec:
  instances: 1
  storage:
    size: 5Gi
  managed:
    roles:
      - name: lldap
        login: true
        passwordSecret:
          name: postgres-auth-lldap-role
      - name: authelia
        login: true
        passwordSecret:
          name: postgres-auth-authelia-role
