apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
spec:
  interval: 30m
  chart:
    spec:
      chart: external-secrets
      sourceRef:
        kind: HelmRepository
        name: external-secrets
      version: "0.18.2"
  driftDetection:
    mode: enabled
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    installCRDs: true
    resources:
      requests:
        cpu: 10m
        memory: 50Mi
      limits:
        memory: 50Mi
    certController:
      resources:
        requests:
          cpu: 10m
          memory: 75Mi
        limits:
          memory: 75Mi
    webhook:
      resources:
        requests:
          cpu: 10m
          memory: 50Mi
        limits:
          memory: 50Mi
