---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-rbnis
  namespace: rbnis
spec:
  secretName: cert-rbnis
  commonName: rbn.is
  dnsNames:
    - rbn.is
    - "*.rbn.is"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
