---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rbnis-canary
  namespace: rbnis
  labels:
    app.kubernetes.io/name: rbnis
    track: canary
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: rbnis
      track: canary
  template:
    metadata:
      labels:
        app.kubernetes.io/name: rbnis
        track: canary
    spec:
      automountServiceAccountToken: false
      containers:
        - name: rbnis
          image: ghcr.io/rbnis/rbn.is:pr-22
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
          resources:
            requests:
              cpu: 25m
              memory: 5Mi
            limits:
              cpu: 150m
              memory: 20Mi
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          securityContext:
            runAsUser: 101
            runAsGroup: 101
            fsGroup: 101
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                topologyKey: "kubernetes.io/hostname"
                labelSelector:
                  matchExpressions:
                    - key: "app"
                      operator: In
                      values:
                        - rbnis
      tolerations:
        - key: "kubernetes.azure.com/scalesetpriority"
          operator: "Equal"
          value: "spot"
          effect: "NoSchedule"
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: rbnis
  namespace: rbnis
spec:
  maxUnavailable: 50%
  selector:
    matchLabels:
      app.kubernetes.io/name: rbnis
      track: canary

