---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: rbnis
  namespace: rbnis
spec:
  selector:
    istio: ingressgateway
  servers:
    - hosts:
        - "rbn.is"
        - "*.rbn.is"
      port:
        number: 80
        name: http
        protocol: HTTP
      tls:
        httpsRedirect: false
    - hosts:
        - "rbn.is"
        - "*.rbn.is"
      port:
        number: 443
        name: https
        protocol: HTTPS
      tls:
        mode: SIMPLE
        credentialName: cert-rbnis
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: rbnis
  namespace: rbnis
spec:
  hosts:
    - "rbn.is"
    - "*.rbn.is"
  gateways:
    - rbnis
  http:
    - match:
        - authority:
            regex: ".*.rbn.is"
      redirect:
        authority: "rbn.is"
        redirectCode: 302
    - route:
        - destination:
            host: rbnis
            port:
              number: 80
