---
apiVersion: azure.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: azure
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: azure-account-creds
      key: credentials
