apiVersion: gateway.networking.k8s.io/v1
kind: TLSRoute
metadata:
  name: kanidm-ldaps
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: ListenerSet
      name: kanidm
      sectionName: ldaps
  hostnames:
    - auth.rbn.is
  rules:
    - backendRefs:
        - name: rbnis
          port: 3636
